Remove now-invalid cops from rubocop (#65)
Because the `lint` check is erroring with:

```
Error: `RSpec/Rails` cops have been extracted to the `rubocop-rspec_rails` gem.
(obsolete configuration found in .rubocop.disabled.yml, please update it)
```

And then:

```
Error: unrecognized cop or department Capybara/MatchStyle found in .rubocop.disabled.yml
unrecognized cop or department Capybara/NegationMatcher found in .rubocop.disabled.yml
unrecognized cop or department Capybara/SpecificActions found in .rubocop.disabled.yml
unrecognized cop or department Capybara/SpecificFinders found in .rubocop.disabled.yml
unrecognized cop or department Capybara/SpecificMatcher found in .rubocop.disabled.yml
unrecognized cop or department FactoryBot/ConsistentParenthesesStyle found in .rubocop.disabled.yml
unrecognized cop or department FactoryBot/FactoryNameStyle found in .rubocop.disabled.yml
unrecognized cop or department FactoryBot/SyntaxMethods found in .rubocop.disabled.yml
```