Allow benchmark scripts to run with ruby `4.0.x` (#123)
This error is currently being shown when trying to run `bundle exec rake
performance[benchmark]` within any Ruby 4.x+:

```
Running performance[benchmark] in rambling-trie:benchmark.017e799.ruby-4.0.3
/usr/rambling-trie/tasks/performance/reporters/benchmark.rb:3: warning: benchmark used to be loaded from the standard library, but is not part of the default gems since Ruby 4.0.0.
You can add benchmark to your Gemfile or gemspec to fix this error.
rake aborted!
LoadError: cannot load such file -- benchmark (LoadError)
```

I thought I had fixed it in #87 by adding both the `benchmark` and the
`irb` gems to the `Gemspec`. Well, turns out the benchmark Dockerfile
uses a significantly reduced version, so that change was not enough.
None of the additions in #112 made a difference either.

This PR:

1. Adds `benchmark` and `benchmark-ips` to minimal `Gemfile` created
   within `Dockerfile.benchmark`
2. Require both gems at the top of the generated `Rakefile` so that we
   fail fast
3. Adds `-n` flag to both `run.sh` and `compare.sh` to allow docker
   builds for the same gem version / git SHA (`--no-cache`)
4. Adds `-V` flag to both `run.sh` and `compare.sh` to allow verbose
   output during docker builds (`--progress=plain`)

---

Also:
- Updates `CONTRIBUTING.md` to clarify `-g` flag usage combined with a
   released gem version
- Suppresses warnings during `Dockerfile.benchmark` runs
- Changes file extension from `.diff` to `.patch`